django_shop/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('shop.urls', namespace='shop')),  # копируем все urls из приложения shop

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    # в режиме отладки добавляем к нашим маршрутам еще один маршрут для статических данных, графических файлов
    # вторым аргументом тут идет папка, где будут идти файлы. На реальных серверах это не нужно, так как уже все настроено
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/shop/urls.py
from django.urls import path

from .views import *

# используем namespacing для удобства. Теперь, к примеру, the product_list URL будет доступен, как shop:product_list в других частях Django проекта.
app_name = 'shop'

urlpatterns = [
    path('', ShopHome.as_view(), name='product_list'),
    path('category/<slug:category_slug>/', ShopCategory.as_view(), name='product_list_by_category'),
    path('category/<slug:category_slug>/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('about/', about, name='about'),
    path('feedback/', FeedbackFormView.as_view(), name='feedback'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),

]

django_shop/shop/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError


class Category(models.Model):
    """Модель для категорий товаров"""
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    class Meta:
        """Используем для задания параметров в админке, без необходимости добавления новых полей в саму модель. """
        ordering = ('name',)  # сортировка применяется и в отображении в админке и в шаблонах
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    """Модель товаров"""
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Доступность')

    class Meta:
        verbose_name = 'Товары'  # отображение названия в админке
        verbose_name_plural = 'Товары'  # отображение названия в админке
        ordering = ('title',)

    def __str__(self):
        return self.title

    # self ссылка на ЭК модели. Через self обращаемся к нужному атрибуту для формирования динамического url и использования в шаблонах.
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.slug,
                                                    self.slug])  # c помощью reverse формируем маршурут с именем shop:product_detail, для этого дополнитнительно  передаем нужные параметры

    def get_average_review_score(self):
        """Вычисляем средний рейтинг товара. self.reviews возвращает все связанные объекты Review для данного объекта Product"""
        average_score = 0.0
        if self.reviews.count() > 0:
            total_score = sum([review.rating for review in self.reviews.all()])
            average_score = total_score / self.reviews.count()
        return round(average_score, 1)


class Review(models.Model):
    """Модель отзывов."""
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE, verbose_name='Продукт')
    author = models.CharField(max_length=50, verbose_name='Автор')
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name='Рейтинг')
    text = models.TextField(blank=True, verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ('-created', )

    def save(self, *args, **kwargs):
        if self.rating > 5 or self.rating < 1:
            raise ValidationError("Неверный рейтинг")
        super().save(*args, **kwargs)

django_shop/shop/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from captcha.fields import CaptchaField

from .models import Review


class RegisterUserForm(UserCreationForm):
    """Форма регистрации пользователей"""
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}), min_length=8,
                                error_messages={'min_length': 'Пароль должен быть длиной не менее 8 символов'})
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароли не совпадают')
        return password2

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 8:
            raise forms.ValidationError('Пароль должен содержать не менее 8 символов.')
        if password1.isdigit():
            raise forms.ValidationError('Пароль должен содержать хотя бы один символ, кроме цифр.')
        return password1

    class Meta:
        model = User  # связываем форму с встроенной моделью User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    """Форма для аутентификации потльзователей"""
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class FeedbackForm(forms.Form):
    """Форма обратной связи"""
    name = forms.CharField(label='Имя', max_length=100)
    email = forms.EmailField(label='Email')
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'cols': 30, 'rows': 4}))
    capatcha = CaptchaField(label='Введите каптчу с картинки')


class ReviewForm(forms.ModelForm):
    """Форма для оставления отзыва на товар"""

    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {
            'text': forms.Textarea(
                attrs={'class': 'form-control shadow px-2',
                       'rows': 6
                       }
            ),
            'rating': forms.RadioSelect
        }

django_shop/shop/views.py
from loguru import logger

from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, FormView, DetailView
from .forms import RegisterUserForm, LoginUserForm, FeedbackForm, ReviewForm
from .models import *
from .utils import DataMixin
from cart.forms import CartAddProductForm

logger.add("debug.log", format="{time} {level} {message}", level="DEBUG", rotation="10 MB")


class ShopHome(DataMixin, ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)  # вызываем родительский метод, чтобы получить базовый контекст
        context['title'] = "Главная"  # добавляем к контексту свои данные, полученные с помощью метода get_user_context
        return dict(list(context.items()))

    def get_queryset(self):
        """Добавляем для оптимизации нагрузки на БД. Благодаря методу select_related у нас происходит
        жадная, а не ленивая загрузка связанных данных  по внешнему FK. В моем случае я уменьшаю количество запросов
        по категориям на главной странице с 11 до 5 (так как в каждом товаре указывается категория)."""
        return Product.objects.all().select_related('category')


class ProductDetailView(DataMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'shop/product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        context['review_form'] = ReviewForm()
        context['cart_product_form'] = CartAddProductForm()
        context = self.get_user_context(**context)
        return context

    def post(self, request, category_slug, slug):
        product = self.get_object()
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            cleaned_form = review_form.cleaned_data
            author_name = "Анонимный пользователь"
            Review.objects.create(
                product=product,
                author=author_name,
                rating=cleaned_form['rating'],
                text=cleaned_form['text']
            )
            return redirect('shop:product_detail', category_slug=category_slug, slug=slug)

        context = self.get_context_data()
        context['review_form'] = review_form
        return self.render_to_response(context)


class ShopCategory(DataMixin, ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'
    allow_empty = False  # генерация ошибки 404 если  нет товаров в категории

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категория - ' + str(context['products'][0].category).upper()
        return dict(list(context.items()))

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'shop/product/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Регистрация')
        context['form_first'] = RegisterUser.form_class
        return dict(list(context.items()) + list(user_context.items()))

    def form_valid(self, form):
        """Встроенный метод который вызывается при успешной регистрации.
        Нужен чтобы зарегистрированного пользователя автоматически авторизовывали.
        Отличие от атрибута success_url в том, что через переменную мы не можем
        после успешной регистрации сразу авторизовать, а также  переменную можно только статический
        адрес указать. Если ссылка формируется динамически - только метод подойдет.
        К примеру, Если я например делаю сайт, где у зарегистрированного пользователя
        есть личная страница,  и я хочу что бы она была по адресу mysite/accounts/<никнейм пользователя>"""
        user = form.save()  # самостоятельно сохраняем пользователя в нашу модель в БД.
        login(self.request, user)  # функция для авторизации пользователя
        return redirect('shop:product_list')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm  # тут мы указываем свою кастомную форму. Изначально пользовались встроенной - класс AutenticationForm
    template_name = 'shop/product/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Войти')
        return dict(list(context.items()) + list(user_context.items()))

    def get_success_url(self):
        return reverse_lazy('shop:product_list')


class FeedbackFormView(DataMixin, FormView):
    form_class = FeedbackForm
    template_name = 'shop/product/feedback.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user_context = self.get_user_context(title='Обратная связь')
        context['form_feedback'] = FeedbackFormView.form_class
        return dict(list(context.items()) + list(user_context.items()))

    def form_valid(self, form):
        logger.debug(form.cleaned_data)  # если форма заполнена корректно, то при отправке логируем данные из формы
        return redirect('shop:product_list')


def about(request):
    return render(request, 'shop/product/about.html')


def logout_user(request):
    logout(request)  # стандартная ф-ия Джанго для выхода из авторизации
    return redirect('shop:login')

django_shop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="{% static 'shop/css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css'  %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
  </head>

<body>
    <!-- Navbar-->
    {% block mainmenu %}
    <div class="header-white">
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-search fixed-top bg-dark">
            <div class="container">
                <a class="navbar-brand text-light" href="{% url 'shop:product_list' %}">
                    <span style="color:#98d98c"><b>Discount wear</b></span>
                </a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle nav-link dropdown-toggle text-light" data-toggle="dropdown" aria-expanded="false" href="#">Категории </a>
                            <div class="dropdown-menu" role="menu">
                                {% for c in categories %}
                                <a class="dropdown-item" role="presentation" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                {% endfor %}
                            </div>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link active text-light" href="{% url 'shop:feedback' %}">Обратная связь</a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link active text-light" href="{% url 'shop:about' %}">О нас</a>
                        </li>
                    </ul>
                    <form class="form-inline mr-auto" target="_self">
                    </form>
                    {% if request.user.is_authenticated %}
                    <span style="color:#4169E1;">{{ user.username }} &nbsp</span>
                    <a class="btn btn-light action-button" role="button" href="{% url 'shop:logout' %}">Выйти</a>
                    {% else %}
                    <a class="btn btn-light action-button" role="button" href="{% url 'shop:login' %}">Войти</a>&nbsp
                    <a class="btn btn-light action-button" role="button" href="{% url 'shop:register' %}">Зарегистрироваться</a>
                    {% endif %}
                </div>
                <a class="ott btn btn-primary" href="{% url 'cart:cart_detail' %}" role="button">
                    <span >Корзина</span>
                </a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <div class="dropdown-custom">
                                <a href="{% url 'cart:cart_detail' %}" class="nav-link text-white drop-btn">
                                    <i class="fas fa-shopping-cart"></i>
                                    ₽<span id="cart_price">{{ cart_total_price }}</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {% endblock mainmenu %}
    <!--End Navbar-->

    <!-- Заголовок с брендом-->
    <header class="bg-light py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-black">
                <h1 class="display-2"><span style="color:#0dfd35"><b> DISCOUNT </b></span> WEAR</h1>
                <p class="lead text-white-50 mb-0">Только качественная одежда по низким ценам!</p>
            </div>
        </div>
    </header>
    <!-- Конец заголовка-->

    <div id="content">
        {% block content %} {% endblock %}
    </div>

    <!-- Пагинация -->
    <br>
    {% if page_obj.has_other_pages %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            </li>
            {% endif %}
            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item active" aria-current="{{ p }}">
                <span class="page-link">{{ p }}</span>
            </li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
            <li class="page-item">
                <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    <!-- Конец пагинации -->

</div>

<!-- Footer-->
<footer class="py-5 bg-dark footer">
    <div class="container">
        <p class="m-0 text-center text-white">Django website by Anastasia 2023
        </p>
    </div>
</footer>
<!-- End footer-->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>