django_shop/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name='cart_remove'),
]

django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('shop.urls', namespace='shop')),  # копируем все urls из приложения shop

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    # в режиме отладки добавляем к нашим маршрутам еще один маршрут для статических данных, графических файлов
    # вторым аргументом тут идет папка, где будут идти файлы. На реальных серверах это не нужно, так как уже все настроено
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create')
]

django_shop/cart/models.py
"""Для хранения информации о корзине используются сесии"""

django_shop/cart/forms.py
from django import forms
from django.forms import NumberInput


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1,
        widget=NumberInput(attrs={
            'class': 'form-control text-center px-3',
            'value': 1
        })
    )

django_shop/cart/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import CartAddProductForm
from .cart_services import Cart


class CartDetailView(View):
    def get(self, request):
        cart = Cart(request)
        cart_items = cart.get_cart_items_with_products()
        cart_total_price = cart.get_cart_total_price(cart_items)
        context = {
            'cart': cart_items,
            'cart_total_price': cart_total_price
        }
        return render(request, 'cart/detail.html', context)


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add_to_cart(product_id, cd['quantity'], request.POST.get('overwrite_qty'))
            return redirect('cart:cart_detail')


class CartRemoveView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        cart.remove_from_cart(product_id)
        return redirect('cart:cart_detail')

django_shop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}

{% block title %}Корзина{% endblock %}

{% block content %}
<div>
    <h3 class="py-2 font-weight-bold text-grey text-center">
        Ваш заказ:
    </h3>
    <div class="row py-2 text-center header-desc">
        <div class="col-lg-2 align-self-center">
            Продукт
        </div>
        <div class="col-lg-2 align-self-center">
            Описание
        </div>
        <div class="col-lg-2 align-self-center">
            Доступность
        </div>
        <div class="col-lg-1 align-self-center">
            Цена
        </div>
        <div class="col-lg-2 align-self-center">
            Количество
        </div>
        <div class="col-lg-3 align-self-center">
            Итоговая цена
        </div>
    </div>
    <hr class="mt-0">
    {% for item in cart %}
        {% with product=item.product %}
            <div class="row justify-content-center cart">
                <div class="cart-item col-4 col-lg-2">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" alt="" class="img-fluid rounded-0">
                    </a>
                </div>
                <div class="cart-item product-name col-12 col-lg-2 align-self-center text-center">
                    {{ product.description }}
                </div>
                <div class="cart-item col-12 col-lg-2 align-self-center">
                    {% if product.available %}
                        <div class="text-green mb-0 text-center">
                            Доступен
                        </div>
                    {% else %}
                        <div class="text-danger mb-0 text-center">
                            Временно недоступен
                        </div>
                    {% endif %}
                </div>
                <div class="cart-item col-12 col-sm-3 col-lg-1 align-self-center text-center">
                    <span>₽{{ product.price }}</span>
                </div>
                <div class="cart-item col-6 col-sm-5 col-lg-2 align-self-center">
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        <span class="input-group shopping-cart">
                            {{ item.update_quantity_form.quantity }}
                            <input type="hidden" name="overwrite_qty" value="True">
                            <div class="input-group-append">
                                <button type="submit" class="btn text-white" data-toggle="tooltip" data-placement="top" title="Update">
                                    <i class="fas fa-edit"></i>
                                </button>
                            </div>
                        </span>
                    </form>
                </div>
                <div class="cart-item col-12 col-sm-3 col-lg-2 align-self-center text-right">
                    <span>₽{{ item.total_price }}</span>
                </div>
                <div class="cart-item col-12 col-lg-1 text-right align-self-center">
                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn" data-toggle="tooltip" data-placement="top" title="Remove">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                </div>
            </div>
        {% endwith %}
    {% empty %}
<div class="align-self-center">
    <span class="text-center font-weight-bold text-muted lead">
        Ваша корзина пуста.
    </span>
</div>
{% endfor %}
<hr>
<div class="total-price-cart">
    <h4 class="row justify-content-center">
        <div>
            Итоговая цена:  <span class="text-danger"> ₽ {{ cart_total_price|floatformat:2 }}</span>
        </div>
        <div class="col-2 col-lg-1">
        </div>
    </h4>
</div>
<hr>
<div class="col-lg-10 mx-auto mb-5">
    <div class="row justify-content-end">
        {% if cart|length > 0 %}
        <div class="col-lg-6 px-0">
            <div class="btn-group d-flex">
                <a href="{% url 'shop:product_list' %}" class="btn btn-warning shadow-custom col">
                    Вернуться назад
                </a>
                <a href="{% url 'orders:order_create' %}" class="btn btn-danger shadow-custom col">
                    Оформить заказ
                </a>
            </div>
        </div>
        {% else %}
        <div class="col-lg-3 px-0">
            <div class="btn-group d-flex">
                <a href="{% url 'shop:product_list' %}" class="btn btn-warning shadow-custom col">
                    Вернуться назад
                </a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}